### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by lensbart** [eddeee888/graphql-code-generator-plugins#218]
When using Yarn (latest) with plug ‘n’ play/zero-installs, some stricter rules on dependencies apply. Specifically, packages can’t import anything not listed in their `package.json`. In this case, it seems like `tslib` is missing.

A workaround is to put the following in `.yarnrc.yml`:

```yml
# .yarnrc.yml
packageExtensions:
  # awaiting fix: https://github.com/eddeee888/graphql-code-generator-plugins/issues/218
  '@eddeee888/gcg-typescript-resolver-files@*':
    dependencies:
      'tslib': '*'
```
