### ISSUE TITLE
[BUG] Disabled mapper resolver generation

### ISSUE THREAD

**Issue by marisbest2** [eddeee888/graphql-code-generator-plugins#317]
(Note, this may be intended behavior in which case consider this a FR)

**Describe the bug**
When I have mappers and `resolverGeneration: disabled` I expect there to not be resolvers generated but there are. 
The docs say 
> **disabled**: generates no resolvers. Use this if you want to use your own structures. Note: if custom scalars are detected and used, resolver main files are still generated.

**To Reproduce**
1. Have mappers
2. Set `resolverGeneration: disabled`
3. Run generate command
4. Observe that resolvers were generated for your mapped types

**Expected behavior**
I expect resolvers to not be generated

**Versions**

- OS: MacOS
- Package name and version: `"@eddeee888/gcg-typescript-resolver-files": "^0.10.2"` (but appears to be long standing behavior)

**Additional context**
Full config:
```yaml
schema: '**/schema.graphql'
generates:
  '.':
    preset: '@eddeee888/gcg-typescript-resolver-files'
    presetConfig:
      mode: modules
      typeDefsFileMode: modules
      resolverGeneration: disabled
      typesPluginsConfig:
        federation: true
        useIndexSignature: true
        resolversNonOptionalTypename: true
      scalarsOverrides:
        ID:
          type: string

hooks: { afterAllFileWrite: ['prettier --write'] }
```

---

**Why I want this:**
I have existing resolvers which all work nicely. Now I'm layering in the types and I don't want to move them all. Mappers should make my life a lot easier. But I definitely don't want to move all my resolvers around.
