### ISSUE TITLE
Upgrading from old graphql-codegen version with different resolver structure

### ISSUE THREAD

**Issue by h-davis-aqovia** [eddeee888/graphql-code-generator-plugins#367]
I am upgrading from a v1 of version of graphql-codegen. The structure and names of resolvers is a lot different

I currently have this structure throughout:
```
company/Company.schema.graphql
company/resolvers/Company.ts (object resolvers)
company/resolvers/Mutation.ts
company/resolvers/Query.ts
```

Is there anyway to specify naming structure? It does not seem to be able to see query or mutation resolvers that do not follow the modern structure (e.g. company/resolvers/Query/company.ts)

resolvers.generated.ts
```
`/* This file was automatically generated. DO NOT UPDATE MANUALLY. */

import    { Company } from './../entities/Company/resolvers/Company';

    export const resolvers: Resolvers = {
      Company: Company,
    }`
```

config.yml
```
`schema: '**/*.graphql'
 generates:
  graphql/generated:
    preset: '@eddeee888/gcg-typescript-resolver-files'
    watchPattern: '**/*.mappers.ts'
    presetConfig:
      typesPluginsConfig: 
        enumsAsTypes: true
        declarationKind: interface
        dedupeOperationSuffix: true
        immutableTypes: true
        namingConvention: keep
        noSchemaStitching: true
        operationResultSuffix: Data
        optionalResolveType: true
        useIndexSignature: true`
```
