### ISSUE TITLE
Property `__typename` can't be optionnal

### ISSUE THREAD

**Issue by Mathieu-Villanueva** [eddeee888/graphql-code-generator-plugins#70]
Hi,
My problem is that all the `__typename` are not optionnal. I've tried to add config field in my `cedegen.yml` file but it doesn't change anything.

Here is an exemple : 
```
type User {
  uuid: String!
  email: String!
  first_name: String
  last_name: String
  username: String
  slug: String
  admin: Boolean
  created_at: DateTime!
  updated_at: DateTime
  campaigns: [Campaign]
  characters: [Character]
}
```

Output :
```
export type User = {
  __typename: 'User';
  admin?: Maybe<Scalars['Boolean']>;
  campaigns?: Maybe<Array<Maybe<Campaign>>>;
  characters?: Maybe<Array<Maybe<Character>>>;
  created_at: Scalars['DateTime'];
  email: Scalars['String'];
  first_name?: Maybe<Scalars['String']>;
  last_name?: Maybe<Scalars['String']>;
  slug?: Maybe<Scalars['String']>;
  updated_at?: Maybe<Scalars['DateTime']>;
  username?: Maybe<Scalars['String']>;
  uuid: Scalars['String'];
};
```

The plugin is great but everytime I make a change on my types, I need to add `?` after every `__typename` in my generated types file.

**Comment by eddeee888** [comment]
Hello! Thanks for using the preset 🙌 

The preset comes with required `__typename` but you can turn it off using `typesPluginsConfig.nonOptionalTypename` option:

```yml
# https://www.graphql-code-generator.com/docs/config-reference/codegen-config
schema: libs/graph-backend/**/*.graphqls
generates:
  src/schemas:
    preset: '@eddeee888/gcg-typescript-resolver-files'
    presetConfig:
      typesPluginsConfig:
        nonOptionalTypename: false
```

Let me know if that works for you :)

**Comment by Mathieu-Villanueva** [comment]
Hi ! 
Thank you Soooooo much !

I was trying to do it like this :
```yml
    preset: '@eddeee888/gcg-typescript-resolver-files'
    config:
      typesPluginsConfig:
        nonOptionalTypename: false
```

And i didn't understand why it wasn't working. Thx again !
